### ISSUE TITLE
Can not add a Microsoft account and Work account with the same email address.

### ISSUE THREAD

**Issue by sdekock** [azure-storage/deco#371]
I both have a Microsoft account and Work (Office 365) account with the same email address.
Each with their own set of subscriptions.
If I try to add either one of them, it replaces the other one.

This does not happen if I add an account with another email address.

**Comment by felixrieseberg** [comment]
Hey @sdekock, good news - we just released a new major version, which should fix that issue. You can grab it directly from http://www.storageexplorer.com!

**Comment by sdekock** [comment]
@felixrieseberg I just grabbed the latest version from the website (0.7.20151116.0) and I still have the same issue.

**Comment by felixrieseberg** [comment]
If it's for the new version, we still really want to hear your feedback - there's a feedback link in the lower left of the new app. The bad news: Most of the engineering team won't be monitoring the issues here.

That makes it obvious though that we should probably close the issues here. Again, thanks a lot - in this case, I'll forward the bug report directly.
